### ISSUE TITLE
misspelling?

### ISSUE THREAD

**Issue by linhongye** [williamg/genetic#1]
genetic.py
line 252
`                child = Organism.getChild(parent1, parent1, self.mutationRate)
`
which should be
`                child = Organism.getChild(parent1, # parent2, self.mutationRate)
`

**Comment by williamg** [comment]
Thanks for pointing that out...surprised it worked as written, but it definitely seems like an error!

**Comment by williamg** [comment]
Should be fixed now, sorry for the late response.
